SELECT COUNT(*) FROM MOVIES

SELECT COUNT(DISTINCT(MOVIE_LANG)) FROM MOVIES

SELECT COUNT(*) FROM MOVIES
WHERE MOVIE_LANG = 'English';


SELECT 
SUM(revenues_domestic) FROM MOVIES_REVENUE

SELECT 
SUM(MOVIE_LENGTH) FROM MOVIES
WHERE MOVIE_LANG = 'English'

SELECT 
MAX (MOVIE_LENGTH) FROM MOVIES;


SELECT 
MIN (MOVIE_LENGTH) FROM MOVIES;

SELECT LEAST ('A','B','C')
SELECT GREATEST (1,2,3,4,5,6)

SELECT AVG(MOVIE_LENGTH) FROM MOVIES

SELECT AVG(DISTINCT(MOVIE_LENGTH)) FROM MOVIES

SELECT 
MOVIE_ID,
REVENUES_DOMESTIC,
REVENUES_INTERNATIONAL,
(REVENUES_DOMESTIC + REVENUES_INTERNATIONAL) AS "TOTAL_REVENUE"
FROM MOVIES_REVENUE


SELECT 
MOVIE_NAME,
RELEASE_DATE,
TO_CHAR (RELEASE_DATE , 'FMMONTH DDTH , YYYY')
FROM MOVIES;

