CREATE TABLE CUSTOMERS(
  CUSTOMER_ID SERIAL PRIMARY KEY,
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  EMAIL VARCHAR(150),
  AGE INT
);

SELECT * FROM CUSTOMERS;

INSERT INTO CUSTOMERS(FIRST_NAME, LAST_NAME, EMAIL, AGE) VALUES 
('MIMANSA', 'MEHTA', 'mimansa@gmail.com', '21')


INSERT INTO CUSTOMERS(FIRST_NAME, LAST_NAME, EMAIL, AGE) VALUES 
('MIMANSA', 'MEHTA', 'mimansa@gmail.com', '21') RETURNING FIRST_NAME;

-- YOU CAN SET COLUMN NAME/VALUES INTO THE COLUMNS 

UPDATE CUSTOMERS
SET AGE = 22
WHERE CUSTOMER_ID = 1
