INSERT INTO PRODUCTS2(NAME, ATTRIBUTES)
VALUES(
'LAPTOP', 
'"COLOR" => "SILVER", "WEIGHT" => "1.5KG", "WARRANTY" => "2 YEARS"'
);

SELECT ATTRIBUTES -> 'COLOR' FROM PRODUCTS2


CREATE TABLE JSON(
ID SERIAL 	PRIMARY KEY,
DOCS JSON
);

SELECT * FROM JSON

INSERT INTO JSON (DOCS) VALUES 
('[1,2,3,4,6,7]'),
('[3,5,5,6,7,8,0]'),
('{"KEY":"VALUE"}');

)