SELECT 
 EXTRACT (DAY FROM CURRENT_TIMESTAMP) AS "DAY",
 EXTRACT (MONTH FROM CURRENT_TIMESTAMP) AS "MONTH",
 EXTRACT (YEAR FROM CURRENT_TIMESTAMP) AS "YEAR";

 SELECT 
 EXTRACT (EPOCH FROM CURRENT_TIMESTAMP);

 SELECT 
 EXTRACT (CENTURY FROM CURRENT_TIMESTAMP);

SELECT 
 '20200101'::DATE + 10

SELECT AGE(CURRENT_DATE, DATE '2003-12-15') AS age;


CREATE TABLE LOGS(
ID SERIAL PRIMARY KEY,
ADD_DATE DATE DEFAULT CURRENT_DATE,
ADD_TIME TIME DEFAULT CURRENT_TIME
);

INSERT INTO LOGS (ID) VALUES ('2')

SELECT * FROM LOGS

DROP TABLE LOGS

SELECT 
  (EXTRACT(EPOCH FROM TIMESTAMPTZ '2020-12-20')- EXTRACT (EPOCH FROM TIMESTAMPTZ '2020-10-20')) 
  /60/60/24 AS "DIFFERENCE IN HOURS"


SHOW TIME ZONE;

SELECT * FROM PG_TIMEZONE_NAMES;


SELECT 
  MOVIE_NAME,
  RELEASE_DATE,
  DATE_PART('WEEK', RELEASE_DATE) AS "RELEASE WEEK",
  DATE_PART('MONTH', RELEASE_DATE) AS "RELEASE MONTH"
FROM 
  MOVIES;


SELECT 
DATE_TRUNC('HOUR', TIMESTAMP '2025-08-05 05:15:23');

SELECT
 DATE_TRUNC('MONTH' , RELEASE_DATE) AS "RELEASE_MONTH",
 COUNT(MOVIE_ID)
 FROM MOVIES
 GROUP BY DATE_TRUNC('MONTH',RELEASE_DATE);