SELECT *
FROM MOVIES
WHERE
  MOVIE_LENGTH > 100
  ORDER BY MOVIE_LENGTH;


SELECT * FROM MOVIES
ORDER BY MOVIE_LENGTH
LIMIT 5;

SELECT * FROM ACTORS
WHERE
  GENDER = 'F'
  ORDER BY DATE_OF_BIRTH DESC
  LIMIT 10;

SELECT * FROM MOVIES_REVENUE
ORDER BY  REVENUES_DOMESTIC DESC
LIMIT 5 OFFSET 5;


SELECT * FROM MOVIES
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM MOVIES
WHERE 
  AGE_LIMIT IN ('12', 'PG')
  ORDER BY AGE_LIMIT;

SELECT * FROM DIRECTORS
WHERE
 DIRECTOR_ID NOT IN ('13', '29')
 ORDER BY DIRECTOR_ID;



SELECT * FROM MOVIES
WHERE
 RELEASE_DATE BETWEEN '2000-01-01' AND '2003-01-01'
 ORDER BY RELEASE_DATE;


SELECT * FROM ACTORS
WHERE 
  FIRST_NAME LIKE 'A%'
  ORDER BY FIRST_NAME


SELECT * FROM ACTORS
WHERE
  DATE_OF_BIRTH IS NULL
  ORDER BY DATE_OF_BIRTH;


SELECT
CONCAT_WS(' , ', FIRST_NAME, LAST_NAME, DATE_OF_BIRTH)
FROM ACTORS
ORDER BY FIRST_NAME;


