SELECT 
 MOVIE_LANG,
 MIN(MOVIE_LENGTH),
 MAX(MOVIE_LENGTH)
 FROM MOVIES
 GROUP BY(MOVIE_LANG);


SELECT 
  MOVIE_LANG,
  AGE_LIMIT,
  AVG(MOVIE_LENGTH) AS "AVG MOVIE LENGTH"
  FROM MOVIES
  WHERE MOVIE_LENGTH > 100	
  GROUP BY MOVIE_LANG, AGE_LIMIT;


SELECT 
 MOVIE_LANG,
 SUM(MOVIE_LENGTH) AS TOTAL_LENGTH
FROM MOVIES
GROUP BY(MOVIE_LANG)
HAVING SUM(MOVIE_LENGTH) > 200
ORDER BY TOTAL_LENGTH;


SELECT 
 DIRECTOR_ID,
 SUM(MOVIE_LENGTH) AS TOTAL_LENGTH
FROM MOVIES
GROUP BY DIRECTOR_ID
HAVING SUM(MOVIE_LENGTH) > 200
ORDER BY TOTAL_LENGTH DESC;

-- HANDLE NULL VALUES 
-- USING COALESCE (SOURCE,'')
-- COALESCE(DEPARTMENT, 'NO DEPARTMENT : EXAMPLE




