SELECT 
  MOVIES.MOVIE_ID,
  MOVIES.MOVIE_NAME,
  MOVIES.DIRECTOR_ID,
  DIRECTORS.FIRST_NAME
FROM 
  MOVIES
INNER JOIN 
  DIRECTORS
ON 
  MOVIES.DIRECTOR_ID = DIRECTORS.DIRECTOR_ID
WHERE 
  MOVIES.MOVIE_LANG = 'English'
  AND DIRECTORS.DIRECTOR_ID = 15;



SELECT * FROM MOVIES
INNER JOIN DIRECTORS USING (DIRECTOR_ID);

SELECT * FROM MOVIES
INNER JOIN MOVIES_REVENUE USING (MOVIE_ID);


SELECT
 MV.MOVIE_NAME,
 D.FIRST_NAME,
 D.LAST_NAME,
 R.REVENUES_DOMESTIC

FROM MOVIES MV
INNER JOIN DIRECTORS D ON MV.DIRECTOR_ID = D.DIRECTOR_ID
INNER JOIN MOVIES_REVENUE R ON MV.MOVIE_ID = R.MOVIE_ID
WHERE
  MV.MOVIE_LANG = 'Japanese'


SELECT
 MV.MOVIE_NAME,
 D.FIRST_NAME,
 D.LAST_NAME,
 R.REVENUES_DOMESTIC,
 R.REVENUES_INTERNATIONAL,

 (R.REVENUES_DOMESTIC + R.REVENUES_INTERNATIONAL) AS "TOTAL REVENUE"

FROM MOVIES MV
INNER JOIN DIRECTORS D ON MV.DIRECTOR_ID = D.DIRECTOR_ID
INNER JOIN MOVIES_REVENUE R ON MV.MOVIE_ID = R.MOVIE_ID
ORDER BY 6 DESC NULLS LAST;



SELECT
 MV.MOVIE_NAME,
 D.FIRST_NAME,
 D.LAST_NAME
 FROM DIRECTORS D
LEFT JOIN MOVIES MV ON MV.DIRECTOR_ID = D.DIRECTOR_ID


SELECT
 D.FIRST_NAME,
 D.LAST_NAME,
 MV.MOVIE_NAME
 FROM MOVIES MV
LEFT JOIN DIRECTORS D ON D.DIRECTOR_ID = MV.DIRECTOR_ID


SELECT
 D.FIRST_NAME,
 D.LAST_NAME,
 MV.MOVIE_NAME
 FROM DIRECTORS D
RIGHT JOIN MOVIES MV ON MV.DIRECTOR_ID = D.DIRECTOR_ID


SELECT
 D.FIRST_NAME,
 D.LAST_NAME,
 MV.MOVIE_NAME
 FROM MOVIES MV
RIGHT JOIN DIRECTORS D ON MV.DIRECTOR_ID = D.DIRECTOR_ID

	
SELECT
 D.FIRST_NAME,
 D.LAST_NAME,
 MV.MOVIE_NAME
 FROM DIRECTORS D
FULL JOIN MOVIES MV ON MV.DIRECTOR_ID = D.DIRECTOR_ID



SELECT * FROM MOVIES MV
JOIN DIRECTORS D ON D.DIRECTOR_ID = MV.DIRECTOR_ID
JOIN MOVIES_REVENUE R ON R.MOVIE_ID = MV.MOVIE_ID


SELECT * FROM DIRECTORS D
JOIN MOVIES MV ON MV.DIRECTOR_ID = D.DIRECTOR_ID
JOIN MOVIES_REVENUE R ON R.MOVIE_ID = MV.MOVIE_ID

SELECT * FROM ACTORS AC
JOIN MOVIE_ACTORS MA ON MA.ACTOR_ID = AC.ACTOR_ID
JOIN MOVIES MV ON MV.MOVIE_ID = MA.MOVIE_ID
JOIN DIRECTORS D ON D.DIRECTOR_ID = MV.DIRECTOR_ID



