CREATE TABLE NET_ADDR(
 ID SERIAL PRIMARY KEY,
 IP INET
);

INSERT INTO NET_ADDR (IP) VALUES
('4.35.221.243'),
('4.152.207.126');

SELECT * FROM NET_ADDR

SELECT
IP, SET_MASKLEN(IP,24) AS INET_24,
    SET_MASKLEN(IP::CIDR,28) AS CIDR_28
FROM NET_ADDR;


