CREATE TABLE T_TAGS(
  ID SERIAL PRIMARY KEY,
  TAG TEXT UNIQUE,
  UPDATE_DATE TIMESTAMP DEFAULT NOW()
);

INSERT INTO T_TAGS (TAG) VALUES
('PEN'),
('PENCIL'),
('ERASER'),
('MARKER');

SELECT * FROM T_TAGS

--UPSERT COMMAND

INSERT INTO T_TAGS(TAG)
VALUES ('PEN')
ON CONFLICT(TAG)
DO UPDATE SET TAG = 'PEN1';

SELECT TAG FROM T_TAGS;


SELECT FIRST_NAME AS "First Name" FROM actors;


-- CONCATENATING OPERATOR WITH ALIAS

SELECT FIRST_NAME||' '|| LAST_NAME AS "FULL NAME" FROM ACTORS;


SELECT * FROM MOVIES
ORDER BY RELEASE_DATE ASC;

SELECT * FROM MOVIES
ORDER BY
 RELEASE_DATE DESC, MOVIE_NAME ASC;


 SELECT 
 FIRST_NAME, LAST_NAME AS "SURNAME" 
 FROM ACTORS
 ORDER BY LAST_NAME ASC;

 SELECT FIRST_NAME,
 LENGTH(FIRST_NAME) AS LEN
 FROM ACTORS
 ORDER BY LEN DESC;


 SELECT 
 FIRST_NAME,
 LAST_NAME,
 DATE_OF_BIRTH
 FROM ACTORS
 ORDER BY
 1 ASC,
 3 DESC;



SELECT
DISTINCT MOVIE_LANG
FROM MOVIES
ORDER BY 1;


SELECT 
DISTINCT*
FROM MOVIES;