CREATE SEQUENCE IF NOT EXISTS TEST_SEQ

SELECT NEXTVAL ('TEST_SEQ')

SELECT CURRVAL('TEST_SEQ')

SELECT SETVAL('TEST_SEQ', 100)

ALTER SEQUENCE TEST_SEQ RESTART WITH 1

ALTER SEQUENCE TEST_SEQ RENAME TO MYSEQ

CREATE SEQUENCE IF NOT EXISTS TESTSEQ
START WITH 500
INCREMENT 50
MINVALUE 400
MAXVALUE 6000;

SELECT NEXTVAL ('TESTSEQ')


CREATE SEQUENCE TESTSEQ1
INCREMENT -1
MINVALUE 1
MAXVALUE 3
START 3
CYCLE;

SELECT NEXTVAL ('TESTSEQ1')

CREATE TABLE USERS2 (
ID SERIAL PRIMARY KEY,
USERNAME VARCHAR(50)
);

INSERT INTO USERS2 (USERNAME) VALUES (
'MIM1'
);

SELECT * FROM USERS2


ALTER SEQUENCE USERS2_ID_SEQ RESTART WITH 100


SELECT RELNAME SEQUENCE_NAME
FROM PG_CLASS
WHERE 
RELKIND = 'S';

CREATE SEQUENCE COMMON_FRUITS_SEQ START WITH 100

CREATE TABLE APPLES (
FRUIT_ID INT DEFAULT NEXTVAL('COMMON_FRUITS_SEQ') NOT NULL,
FRUITS_NAME VARCHAR(50)
);

CREATE TABLE MANGOES (
FRUIT_ID INT DEFAULT NEXTVAL('COMMON_FRUITS_SEQ') NOT NULL,
FRUITS_NAME VARCHAR(50)
);

INSERT INTO MANGOES (FRUITS_NAME) VALUES ('MANGOES');
SELECT * FROM MANGOES


