CREATE TABLE TABLE_BOOLEAN(
PRODUCT_ID SERIAL PRIMARY KEY,	
IS_AVAILABLE BOOLEAN NOT NULL
);

INSERT INTO TABLE_BOOLEAN(IS_AVAILABLE) VALUES (TRUE)

SELECT * FROM TABLE_BOOLEAN

ALTER TABLE TABLE_BOOLEAN
ALTER COLUMN IS_AVAILABLE
SET DEFAULT '0'


CREATE TABLE TABLE_CHAR(
 COL_CHAR CHAR(10),
 COL_VARCHAR VARCHAR(10),
 COL_TXT TEXT
);


INSERT INTO TABLE_CHAR(COL_CHAR,COL_VARCHAR,COL_TXT) VALUES
('ABC','ABC','ABC'),
('xyz', 'xyz', 'xyz');

SELECT * FROM TABLE_CHAR

CREATE TABLE TABLE_DATES(
ID SERIAL PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(100) NOT NULL,
HIRE_DATE DATE NOT NULL,
ADD_DATE DATE DEFAULT CURRENT_DATE
);

INSERT INTO TABLE_DATES (EMPLOYEE_NAME, HIRE_DATE) VALUES
('MIM', '2025-07-02'),
('AMIT', '2000-06-01');

SELECT * FROM TABLE_DATES

SELECT CURRENT_TIME;

SELECT CURRENT_TIME(4);

SET TIMEZONE = 'AMERICA/NEW_YORK'
SELECT CURRENT_TIMESTAMP;
SELECT TIMEOFDAY();

CREATE EXTENSION IF NOT EXISTS "UUID-OSSP";
SELECT UUID_GENERATE_V1();

SELECT UUID_GENERATE_V4();

CREATE TABLE TABLE_UUID(
PRODUCT_ID UUID DEFAULT UUID_GENERATE_V1(),
PRODUCT_NAME VARCHAR(100) NOT NULL
);

INSERT INTO TABLE_UUID (PRODUCT_NAME) VALUES ('ABC1');

SELECT * FROM TABLE_UUID;


CREATE TABLE TAB_ARR(
 ID SERIAL,
 NAME VARCHAR(50),
 PHONES TEXT[]
);

INSERT INTO TAB_ARR(NAME, PHONES) VALUES
('MIM', ARRAY['9871689126', '4566878013']),
('AMIT', ARRAY['7920721345', '6756833423'])

SELECT NAME , PHONES[1] FROM TAB_ARR

CREATE EXTENSION IF NOT EXISTS HSTORE

CREATE TABLE PRODUCTS2(
ID SERIAL PRIMARY KEY,
NAME TEXT,
ATTRIBUTES HSTORE
);


INSERT INTO PRODUCTS2(NAME, ATTRIBUTES)
VALUES(
'LAPTOP', 
'"COLOR" => "SILVER", "WEIGHT" => "1.5KG", "WARRANTY" => "2 YEARS"'
);

SELECT * FROM PRODUCTS2