SELECT UPPER ('Mimansa')
SELECT lower ('Mimansa')
SELECT INITCAP ('Mimansa MEHTA')

SELECT LEFT ('MIAMI', 1)
SELECT LEFT ('MIAMI', 3)

SELECT LEFT (FIRST_NAME,1) AS INITIAL
FROM DIRECTORS
ORDER BY 1;

SELECT REVERSE ('LEO MESSI')

SELECT SPLIT_PART ('ONE,TWO,THREE', ',',3)

SELECT MOVIE_NAME,RELEASE_DATE,SPLIT_PART(RELEASE_DATE::TEXT,'-','1') AS RELEASE_YEAR
FROM MOVIES;

SELECT * FROM MOVIES;



SELECT TRIM(BOTH 'x' FROM 'xxxabcxxx'); 
SELECT TRIM(LEADING 'x' FROM 'xxxabcxxx');
SELECT TRIM(TRAILING 'x' FROM 'xxxabcxxx'); 


SELECT LTRIM('xxxyabc', 'xy');         


SELECT RTRIM('abcxyx', 'xy');          

SELECT BTRIM('xyabcxy', 'xy');        

SELECT LPAD('123', 6, '0');      

SELECT RPAD('123', 6, '0'); 
SELECT RPAD('abc', 2, '!');       


SELECT LENGTH ('HELLO HI HOW ARE YOU')

SELECT POSITION ('IS' IN 'MY NAME NAME IS HENRY')

SELECT STRPOS ('HENRYCAVILL', 'CAVILL')

SELECT SUBSTRING ('MY NAME IS LEO' FROM 4 FOR 14)


SELECT REPEAT ('MIM', 15);

SELECT REPLACE ('I LIKE LEO, MAX, HENRY, MS', 'MS', 'DHONI')



